### ISSUE TITLE
Empty object render fix is broken

### ISSUE THREAD

**Issue by Lothrik** [pgrabovets/json-view#17]
The fix for #11 implemented in #12 does not work correctly:
```
jsonview.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C (jsonview.js:1:6656)
    at I (jsonview.js:1:6905)
    at I (jsonview.js:1:6984)
    at I (jsonview.js:1:6984)
    at I (jsonview.js:1:6984)
    at I (jsonview.js:1:6984)
    at I (jsonview.js:1:6984)
    at Module.S (jsonview.js:1:7118)
    at Object.success (data.js:71:24)
```

https://github.com/pgrabovets/json-view/blob/26a04fef47455a7e4418e604a40cde2baeda45e5/src/json-view.js#L153

``typeof null == 'object'`` is true — meaning ``Object.keys(null)`` is called and immediately throws the above error. ``null`` does not have its own type like ``undefined`` does.

**Comment by pgrabovets** [comment]
Thanks for helping me. I have fixed it. Should work properly.
